name: flutterclient
description: An open-source short video sharing platform that respects your privacy.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
    path: ../flutter-plugins/packages/camera
  flutter_ffmpeg: ^0.2.10
  graphql_flutter: "^3.0.0"
  video_player: ">=0.10.5 <2.0.0"
  image_picker: ">=0.6.7"
  logger: "^0.6.0"
  device_info: ">=0.4.0 <2.0.0"
  shared_preferences: '>=0.5.0 <2.0.0'
  google_sign_in: ">=4.5.1"
  path_provider: ">=1.6.11"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
  assets:
    - assets/images/