/// Flutter icons FontAwesome
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontAwesome
///      fonts:
///       - asset: fonts/FontAwesome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FontAwesome {
  FontAwesome._();

  static const _kFontFam = 'FontAwesome';
  static const _kFontPkg = null;

  static const IconData share_solid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_lines_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_plus_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_h_regular = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_solid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_solid = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
