/// Flutter icons FontAwesome
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class FontAwesome {
  FontAwesome._();

  static const _kFontFam = 'FontAwesome';
  static const _kFontPkg = null;

  static const IconData share_solid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_lines_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_plus_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_h_regular = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
